openshift.withCluster() {
  env.APP_NAME = "${APP_NAME}"
  env.BUILD = openshift.project()
  env.DEV = "${DEV_PROJECT}"
  env.STAGE = "${STAGE_PROJECT}"
  echo "Starting Pipeline for ${APP_NAME}..."
}

pipeline {
  agent {
    label 'node12-agent'
  }


  stages {
    stage('Git Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Unit Test') {


	steps {
      
         //input message: "Wait a sec?", ok: "Promote"

         script {
           sh "node --version"
           //sh "yarn -h"
           //sh "dos2unix -h"
           sh "npm install"
           sh "npm test"
         }
       }
   }


    stage('Build Image') {
       
       steps {
         script {

            sh """ 
                echo "AP: ${APP_NAME}"
                oc patch bc ssr-app-shell --type=json '-p=[{"op": "replace", "path": "/spec/output/to/name", "value": ${APP_NAME}}]'
            """
             openshift.withCluster() {
              openshift.withProject(env.DEV_PROJECT) {
                sh "pwd; ls -lrt"
                openshift.selector("bc", "node-test").startBuild("--from-dir=.", "--wait=true")
              }
            }
         }
       }
   }


   stage('Deploy DEV') {
      steps {
         script {
            openshift.withCluster() {
              openshift.withProject(env.DEV_PROJECT) {
                openshift.selector("dc", "${APP_NAME}").rollout().latest();
              }
            }
        }
     }
   }

   stage('Promote to Stage') {
      steps {
          timeout(time:15, unit:'MINUTES') {
             input message: "Promote to STAGE?", ok: "Promote"
         }

         script {
            openshift.withCluster() {
                openshift.tag("${env.DEV_PROJECT}/${APP_NAME}:latest", "${env.STAGE_PROJECT}/${APP_NAME}:latest")
            }
        }
     }
   }


   stage('Deploy Stage') {
      steps {
         script {
            openshift.withCluster() {
              openshift.withProject(env.STAGE_PROJECT) {
                openshift.selector("dc", "${APP_NAME}").rollout().latest();
              }
            }
        }
     }
   }


  }
}

println "Application ${env.APP_NAME} is now in Production!"


